export const mockEmployees = [
  {
    id: 'emp-001',
    name: '관리자',
    empNo: 'A001',
    phone: '010-1234-0000',
    role: 'admin',
    jobType: '관리',
    hireDate: '2024-01-15',
    workHoursPerWeek: 40,
    annualLeaveDays: 15,
    pinCode: '000000',
    isActive: true,
  },
  {
    id: 'emp-002',
    name: '김민국',
    empNo: 'W001',
    phone: '010-1234-1111',
    role: 'worker',
    jobType: '재배',
    hireDate: '2024-03-01',
    workHoursPerWeek: 40,
    annualLeaveDays: 15,
    pinCode: '111111',
    isActive: true,
  },
  {
    id: 'emp-003',
    name: '이강모',
    empNo: 'W002',
    phone: '010-1234-2222',
    role: 'worker',
    jobType: '재배',
    hireDate: '2024-03-01',
    workHoursPerWeek: 40,
    annualLeaveDays: 15,
    pinCode: '222222',
    isActive: true,
  },
  {
    id: 'emp-004',
    name: '박민식',
    empNo: 'W003',
    phone: '010-1234-3333',
    role: 'worker',
    jobType: '재배',
    hireDate: '2024-04-15',
    workHoursPerWeek: 40,
    annualLeaveDays: 15,
    pinCode: '333333',
    isActive: true,
  },
  {
    id: 'emp-005',
    name: '최수진',
    empNo: 'W004',
    phone: '010-1234-4444',
    role: 'worker',
    jobType: '관리',
    hireDate: '2024-06-01',
    workHoursPerWeek: 40,
    annualLeaveDays: 15,
    pinCode: '444444',
    isActive: true,
  },
];

export const mockCrops = [
  {
    id: 'crop-001',
    name: '토마토',
    taskTypes: ['수확', '유인·결속', '적엽', '병해충 예찰', 'EC/pH 측정', '수분 작업'],
    isActive: true,
  },
  {
    id: 'crop-002',
    name: '오이',
    taskTypes: ['수확', '유인·결속', '적엽', '병해충 예찰', 'EC/pH 측정'],
    isActive: true,
  },
  {
    id: 'crop-003',
    name: '미니파프리카',
    taskTypes: ['수확', '유인·결속', '적엽', '병해충 예찰', 'EC/pH 측정', '수분 작업'],
    isActive: true,
  },
  {
    id: 'crop-004',
    name: '딸기',
    taskTypes: ['수확', '러너 정리', '적엽', '병해충 예찰', 'EC/pH 측정'],
    isActive: true,
  },
];

export const mockZones = [
  { id: 'zone-001', name: 'A동', description: '토마토 재배동', rowCount: 20, plantCount: 400 },
  { id: 'zone-002', name: 'B동', description: '오이·파프리카 재배동', rowCount: 16, plantCount: 320 },
  { id: 'zone-003', name: 'C동', description: '딸기 재배동', rowCount: 24, plantCount: 600 },
];
