-- ═══════════════════════════════════════════════════════════
-- Phase 3B: 생육조사 확장
-- p3a.sql 실행 완료 후 실행할 것
-- ═══════════════════════════════════════════════════════════

-- ─── STEP 1: 표식주 테이블 ───
CREATE TABLE IF NOT EXISTS marker_plants (
  id            uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
  crop_id       uuid  NOT NULL REFERENCES crops(id),
  branch        text  NOT NULL,
  greenhouse_id uuid  REFERENCES greenhouses(id),
  bed           text  NOT NULL,
  row_label     text  NOT NULL,
  plant_no      int   NOT NULL,
  start_date    date  NOT NULL,
  health        text  DEFAULT 'good' CHECK (health IN ('good','warn','critical')),
  note          text,
  is_active     bool  DEFAULT true,
  created_at    timestamptz DEFAULT now()
);

-- ─── STEP 2: 표준 곡선 ───
CREATE TABLE IF NOT EXISTS standard_curves (
  id           uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  crop_id      uuid    NOT NULL REFERENCES crops(id),
  season       text,
  metric_key   text    NOT NULL,
  week         int     NOT NULL,
  target_value numeric NOT NULL,
  created_at   timestamptz DEFAULT now(),
  UNIQUE(crop_id, season, metric_key, week)
);

-- ─── STEP 3: growth_surveys에 표식주 FK ───
ALTER TABLE growth_surveys ADD COLUMN IF NOT EXISTS marker_plant_id uuid REFERENCES marker_plants(id);

-- ─── STEP 4: RLS ───
ALTER TABLE marker_plants   ENABLE ROW LEVEL SECURITY;
ALTER TABLE standard_curves ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='marker_plants' AND policyname='marker_plants_admin_all') THEN
    CREATE POLICY "marker_plants_admin_all"    ON marker_plants FOR ALL    USING (is_admin_level());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='marker_plants' AND policyname='marker_plants_anon_select') THEN
    CREATE POLICY "marker_plants_anon_select"  ON marker_plants FOR SELECT TO anon USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='standard_curves' AND policyname='standard_curves_admin_all') THEN
    CREATE POLICY "standard_curves_admin_all"   ON standard_curves FOR ALL    USING (is_admin_level());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='standard_curves' AND policyname='standard_curves_anon_select') THEN
    CREATE POLICY "standard_curves_anon_select" ON standard_curves FOR SELECT TO anon USING (true);
  END IF;
END $$;

-- ─── STEP 5: standard_curves 시드 ───
-- 3작물(토마토/오이/파프리카) × 11지표 × 12주 = 396행
-- season = '2026' (현재 작기)

INSERT INTO standard_curves (crop_id, season, metric_key, week, target_value) VALUES

-- ── 토마토 ──
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',1,18),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',2,20),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',3,22),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',4,24),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',5,25),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',6,26),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',7,26),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',8,25),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',9,24),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',10,23),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',11,22),
((SELECT id FROM crops WHERE name='토마토'),'2026','weeklyGrowth',12,20),

((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',1,28),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',2,32),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',3,35),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',4,37),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',5,38),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',6,39),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',7,39),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',8,38),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',9,37),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',10,36),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',11,35),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafLen',12,34),

((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',1,24),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',2,27),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',3,29),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',4,31),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',5,32),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',6,32),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',7,32),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',8,31),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',9,30),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',10,30),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',11,29),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafWid',12,28),

((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',1,14),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',2,16),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',3,18),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',4,20),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',5,22),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',6,23),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',7,24),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',8,24),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',9,24),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',10,23),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',11,22),
((SELECT id FROM crops WHERE name='토마토'),'2026','leafPerStem',12,22),

((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',1,10.0),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',2,10.8),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',3,11.4),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',4,11.8),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',5,12.0),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',6,12.0),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',7,11.8),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',8,11.6),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',9,11.4),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',10,11.2),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',11,11.0),
((SELECT id FROM crops WHERE name='토마토'),'2026','stemDia',12,10.8),

((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',1,95),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',2,110),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',3,125),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',4,140),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',5,155),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',6,170),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',7,185),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',8,200),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',9,215),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',10,230),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',11,245),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterH',12,260),

((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',1,12),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',2,13),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',3,14),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',4,15),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',5,15),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',6,16),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',7,16),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',8,16),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',9,15),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',10,15),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',11,14),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerClusterLen',12,14),

((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',1,2),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',2,3),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',3,3),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',4,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',5,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',6,5),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',7,5),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',8,5),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',9,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',10,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',11,3),
((SELECT id FROM crops WHERE name='토마토'),'2026','flowerCount',12,3),

((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',1,1),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',2,2),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',3,3),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',4,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',5,5),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',6,6),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',7,7),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',8,7),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',9,7),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',10,6),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',11,5),
((SELECT id FROM crops WHERE name='토마토'),'2026','fruitSetCluster',12,4),

((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',1,0),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',2,0),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',3,0),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',4,1),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',5,2),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',6,3),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',7,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',8,5),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',9,6),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',10,6),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',11,6),
((SELECT id FROM crops WHERE name='토마토'),'2026','harvestCluster',12,6),

((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',1,4),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',2,10),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',3,18),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',4,28),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',5,40),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',6,54),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',7,68),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',8,82),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',9,95),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',10,106),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',11,115),
((SELECT id FROM crops WHERE name='토마토'),'2026','totalFruit',12,122),

-- ── 오이 ──
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',1,22),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',2,26),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',3,28),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',4,30),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',5,31),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',6,32),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',7,32),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',8,31),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',9,30),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',10,28),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',11,26),
((SELECT id FROM crops WHERE name='오이'),'2026','weeklyGrowth',12,24),

((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',1,20),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',2,23),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',3,25),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',4,27),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',5,28),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',6,28),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',7,28),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',8,27),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',9,26),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',10,26),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',11,25),
((SELECT id FROM crops WHERE name='오이'),'2026','leafLen',12,24),

((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',1,22),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',2,25),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',3,27),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',4,29),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',5,30),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',6,30),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',7,29),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',8,28),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',9,28),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',10,27),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',11,26),
((SELECT id FROM crops WHERE name='오이'),'2026','leafWid',12,25),

((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',1,16),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',2,20),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',3,24),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',4,28),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',5,32),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',6,35),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',7,37),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',8,37),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',9,36),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',10,34),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',11,32),
((SELECT id FROM crops WHERE name='오이'),'2026','leafCount',12,30),

((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',1,9.0),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',2,9.6),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',3,10.0),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',4,10.4),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',5,10.6),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',6,10.6),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',7,10.4),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',8,10.2),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',9,10.0),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',10,9.8),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',11,9.6),
((SELECT id FROM crops WHERE name='오이'),'2026','stemDia',12,9.4),

((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',1,60),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',2,80),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',3,100),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',4,120),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',5,140),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',6,160),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',7,180),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',8,200),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',9,220),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',10,240),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',11,260),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterH',12,280),

((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',1,6),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',2,7),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',3,8),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',4,8),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',5,9),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',6,9),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',7,9),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',8,8),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',9,8),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',10,7),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',11,7),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerClusterLen',12,6),

((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',1,3),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',2,5),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',3,7),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',4,9),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',5,11),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',6,12),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',7,12),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',8,11),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',9,10),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',10,9),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',11,8),
((SELECT id FROM crops WHERE name='오이'),'2026','flowerCluster',12,7),

((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',1,2),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',2,4),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',3,6),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',4,8),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',5,10),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',6,11),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',7,11),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',8,10),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',9,9),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',10,8),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',11,7),
((SELECT id FROM crops WHERE name='오이'),'2026','fruitSetCluster',12,6),

((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',1,0),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',2,1),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',3,2),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',4,4),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',5,6),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',6,8),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',7,10),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',8,10),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',9,10),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',10,9),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',11,8),
((SELECT id FROM crops WHERE name='오이'),'2026','harvestCluster',12,7),

((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',1,2),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',2,6),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',3,12),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',4,20),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',5,30),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',6,42),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',7,55),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',8,66),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',9,76),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',10,84),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',11,90),
((SELECT id FROM crops WHERE name='오이'),'2026','totalFruit',12,95),

-- ── 파프리카 ──
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',1,15),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',2,17),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',3,19),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',4,21),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',5,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',6,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',7,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',8,21),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',9,20),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',10,19),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',11,18),
((SELECT id FROM crops WHERE name='파프리카'),'2026','weeklyGrowth',12,16),

((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',1,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',2,25),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',3,27),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',4,29),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',5,30),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',6,30),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',7,30),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',8,29),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',9,28),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',10,27),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',11,26),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafLen',12,25),

((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',1,18),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',2,21),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',3,23),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',4,25),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',5,26),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',6,26),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',7,26),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',8,25),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',9,24),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',10,23),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',11,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafWid',12,21),

((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',1,12),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',2,15),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',3,17),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',4,19),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',5,21),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',6,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',7,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',8,22),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',9,21),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',10,20),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',11,19),
((SELECT id FROM crops WHERE name='파프리카'),'2026','leafPerStem',12,18),

((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',1,11.0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',2,11.8),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',3,12.4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',4,12.8),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',5,13.0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',6,13.0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',7,12.8),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',8,12.6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',9,12.4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',10,12.2),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',11,12.0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','stemDia',12,11.8),

((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',1,70),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',2,85),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',3,100),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',4,115),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',5,130),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',6,145),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',7,160),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',8,175),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',9,190),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',10,205),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',11,220),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterH',12,235),

((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',1,8),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',2,9),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',3,10),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',4,10),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',5,11),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',6,11),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',7,11),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',8,10),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',9,10),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',10,9),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',11,9),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerClusterLen',12,8),

((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',1,3),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',2,4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',3,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',4,6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',5,6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',6,7),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',7,7),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',8,6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',9,6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',10,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',11,4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','flowerCount',12,4),

((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',1,1),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',2,2),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',3,3),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',4,4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',5,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',6,6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',7,7),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',8,7),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',9,6),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',10,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',11,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','fruitSetCluster',12,4),

((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',1,0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',2,0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',3,0),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',4,1),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',5,2),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',6,3),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',7,4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',8,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',9,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',10,5),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',11,4),
((SELECT id FROM crops WHERE name='파프리카'),'2026','harvestCluster',12,4),

((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',1,3),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',2,8),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',3,15),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',4,24),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',5,34),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',6,45),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',7,56),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',8,66),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',9,74),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',10,80),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',11,85),
((SELECT id FROM crops WHERE name='파프리카'),'2026','totalFruit',12,88)

ON CONFLICT (crop_id, season, metric_key, week) DO NOTHING;

-- ─── 확인 ───
SELECT count(*) AS standard_curve_rows FROM standard_curves;
SELECT count(*) AS marker_plant_count  FROM marker_plants;
